#!/usr/bin/env python3
"""Freeze normalized_catalog.csv into benchmark_catalog_frozen.csv.

Run exactly once when starting Checkpoint 3 benchmark authoring. Every
benchmark script (build_candidate_pool.py, tfidf_baseline.py, ...) reads the
frozen copy, never the live normalized_catalog.csv -- that file gets
regenerated by build_normalized_catalog.py as scrapes are re-run, and a
benchmark whose "correct answer" catalog silently drifted out from under it
would invalidate every review decision made against it.

Writes/refreshes benchmark_manifest.json's catalog identity (sha256, row
count, freeze timestamp) -- the catalog_version every label_review_ui.py
decision stamps itself with. Refuses to overwrite an existing frozen catalog
+ manifest silently: re-freezing is a deliberate action (a new catalog
version), not something to do by accident mid-benchmark.
"""
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "normalized_catalog.csv"
FROZEN = HERE / "benchmark_catalog_frozen.csv"
MANIFEST = HERE / "benchmark_manifest.json"


def main():
    if FROZEN.exists() and "--force" not in sys.argv:
        print(
            f"{FROZEN.name} already exists. Re-freezing changes catalog_version and "
            "stales every existing review decision. Pass --force to proceed anyway.",
            file=sys.stderr,
        )
        sys.exit(1)

    content = SOURCE.read_bytes()
    FROZEN.write_bytes(content)

    with open(FROZEN, newline="", encoding="utf-8") as f:
        row_count = sum(1 for _ in f) - 1  # minus header

    catalog_version = {
        "sha256": hashlib.sha256(content).hexdigest(),
        "row_count": row_count,
        "frozen_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ"),
        "source_file": SOURCE.name,
    }

    manifest = {}
    if MANIFEST.exists():
        manifest = json.loads(MANIFEST.read_text())
    manifest["catalog_version"] = catalog_version
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"Froze {row_count} rows to {FROZEN.name}")
    print(f"catalog_version: {catalog_version}")


if __name__ == "__main__":
    main()
